-- Generated from the miner's `slot/src/parse.rs` by `verifier/extract.sh`
-- (charon + aeneas). Never hand-edited; regenerated by the verifier on every
-- submission, so an extraction supplied by a miner is never trusted.
import Slot.Types
import Slot.Funs
import Slot.Constants
