-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slot]: function definitions
import Aeneas
import Slot.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slot

/-- [slot::MIN_MATCH]
    Source: 'src/parse.rs', lines 42:0-42:31
    Visibility: public -/
@[global_simps, irreducible] def MIN_MATCH : Std.Usize := 3#usize

/-- [slot::MAX_MATCH]
    Source: 'src/parse.rs', lines 43:0-43:33
    Visibility: public -/
@[global_simps, irreducible] def MAX_MATCH : Std.Usize := 258#usize

/-- [slot::WINDOW]
    Source: 'src/parse.rs', lines 44:0-44:32
    Visibility: public -/
@[global_simps, irreducible] def WINDOW : Std.Usize := 32768#usize

/-- [slot::HASH_SIZE]
    Source: 'src/parse.rs', lines 45:0-45:35
    Visibility: public -/
@[global_simps, irreducible] def HASH_SIZE : Std.Usize := 32768#usize

/-- [slot::MAX_PROBES]
    Source: 'src/parse.rs', lines 48:0-48:33
    Visibility: public -/
@[global_simps, irreducible] def MAX_PROBES : Std.Usize := 16#usize

/-- [slot::hash3]:
    Source: 'src/parse.rs', lines 52:0-58:1
    Visibility: public -/
def hash3 (a : Std.U8) (b : Std.U8) (c : Std.U8) : Result Std.Usize := do
  let i ← lift (UScalar.cast .U32 a)
  let i1 ← lift (core.num.U32.wrapping_mul i 2654435761#u32)
  let i2 ← lift (UScalar.cast .U32 b)
  let i3 ← lift (core.num.U32.wrapping_mul i2 2246822519#u32)
  let i4 ← lift (core.num.U32.wrapping_add i1 i3)
  let i5 ← lift (UScalar.cast .U32 c)
  let i6 ← lift (core.num.U32.wrapping_mul i5 3266489917#u32)
  let x ← lift (core.num.U32.wrapping_add i4 i6)
  let i7 ← x >>> 15#i32
  let i8 ← i7 % 32768#u32
  ok (UScalar.cast .Usize i8)

/-- [slot::match_len]: loop body 0:
    Source: 'src/parse.rs', lines 1:0-66:5
    Visibility: public -/
@[rust_loop_body]
def match_len_loop.body
  (input : Slice Std.U8) (a : Std.Usize) (b : Std.Usize) (cap : Std.Usize)
  (l : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if l < cap
  then
    let i ← b + l
    let i1 ← Slice.index_usize input i
    let i2 ← a + l
    let i3 ← Slice.index_usize input i2
    if i1 = i3
    then let l1 ← l + 1#usize
         ok (cont l1)
    else ok (done l)
  else ok (done l)

/-- [slot::match_len]: loop 0:
    Source: 'src/parse.rs', lines 1:0-66:5
    Visibility: public -/
@[rust_loop]
def match_len_loop
  (input : Slice Std.U8) (a : Std.Usize) (b : Std.Usize) (cap : Std.Usize)
  (l : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun l1 => match_len_loop.body input a b cap l1)
    l

/-- [slot::match_len]:
    Source: 'src/parse.rs', lines 62:0-68:1
    Visibility: public -/
@[reducible]
def match_len
  (input : Slice Std.U8) (a : Std.Usize) (b : Std.Usize) (cap : Std.Usize) :
  Result Std.Usize
  := do
  match_len_loop input a b cap 0#usize

/-- [slot::find_match]: loop body 0:
    Source: 'src/parse.rs', lines 1:0-105:5
    Visibility: public -/
@[rust_loop_body]
def find_match_loop.body
  (input : Slice Std.U8) (prev : Slice Std.U32) (pos : Std.Usize)
  (cap : Std.Usize) (best_len : Std.Usize) (best_dist : Std.Usize)
  (cur : Std.Usize) (probes : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize × Std.Usize × Std.Usize)
    (Std.Usize × Std.Usize))
  := do
  if probes < 16#usize
  then
    if cur > 0#usize
    then
      if cur <= pos
      then
        let cpos ← cur - 1#usize
        let i ← pos - cpos
        let (best_len1, best_dist1, cur1) ←
          if i <= 32768#usize
          then
            do
            let l ← match_len input cpos pos cap
            let (best_len2, best_dist2) ←
              if l > best_len
              then ok (l, i)
              else ok (best_len, best_dist)
            let i1 ← cpos % 32768#usize
            let i2 ← Slice.index_usize prev i1
            let cur2 ← lift (UScalar.cast .Usize i2)
            ok (best_len2, best_dist2, cur2)
          else ok (best_len, best_dist, 0#usize)
        let probes1 ← probes + 1#usize
        ok (cont (best_len1, best_dist1, cur1, probes1))
      else ok (done (best_len, best_dist))
    else ok (done (best_len, best_dist))
  else ok (done (best_len, best_dist))

/-- [slot::find_match]: loop 0:
    Source: 'src/parse.rs', lines 1:0-105:5
    Visibility: public -/
@[rust_loop]
def find_match_loop
  (input : Slice Std.U8) (prev : Slice Std.U32) (pos : Std.Usize)
  (cap : Std.Usize) (best_len : Std.Usize) (best_dist : Std.Usize)
  (cur : Std.Usize) (probes : Std.Usize) :
  Result (Std.Usize × Std.Usize)
  := do
  loop
    (fun (best_len1, best_dist1, cur1, probes1) => find_match_loop.body input
      prev pos cap best_len1 best_dist1 cur1 probes1)
    (best_len, best_dist, cur, probes)

/-- [slot::find_match]:
    Source: 'src/parse.rs', lines 79:0-107:1
    Visibility: public -/
@[reducible]
def find_match
  (input : Slice Std.U8) (prev : Slice Std.U32) (pos : Std.Usize)
  (cap : Std.Usize) (start : Std.Usize) :
  Result (Std.Usize × Std.Usize)
  := do
  find_match_loop input prev pos cap 0#usize 0#usize start 0#usize

/-- [slot::parse]: loop body 1:
    Source: 'src/parse.rs', lines 1:0-154:13
    Visibility: public -/
@[rust_loop_body]
def parse_loop0_loop0.body
  (input : Slice Std.U8) (lim : Std.Usize) («end» : Std.Usize)
  (head : Array Std.U32 32768#usize) (prev : Array Std.U32 32768#usize)
  (has3 : Bool) (k : Std.Usize) :
  Result (ControlFlow ((Array Std.U32 32768#usize) × (Array Std.U32
    32768#usize) × Bool × Std.Usize) ((Array Std.U32 32768#usize) × (Array
    Std.U32 32768#usize) × Bool))
  := do
  if k < «end»
  then
    if has3
    then
      if k <= lim
      then
        let i ← Slice.index_usize input k
        let i1 ← k + 1#usize
        let i2 ← Slice.index_usize input i1
        let i3 ← k + 2#usize
        let i4 ← Slice.index_usize input i3
        let h2 ← hash3 i i2 i4
        let i5 ← Array.index_usize head h2
        let i6 ← k % 32768#usize
        let a ← Array.update prev i6 i5
        let i7 ← lift (UScalar.cast .U32 i1)
        let a1 ← Array.update head h2 i7
        ok (cont (a1, a, true, i1))
      else ok (done (head, prev, true))
    else ok (done (head, prev, false))
  else ok (done (head, prev, has3))

/-- [slot::parse]: loop 1:
    Source: 'src/parse.rs', lines 1:0-154:13
    Visibility: public -/
@[rust_loop]
def parse_loop0_loop0
  (input : Slice Std.U8) (head : Array Std.U32 32768#usize)
  (prev : Array Std.U32 32768#usize) (has3 : Bool) (lim : Std.Usize)
  («end» : Std.Usize) (k : Std.Usize) :
  Result ((Array Std.U32 32768#usize) × (Array Std.U32 32768#usize) × Bool)
  := do
  loop
    (fun (head1, prev1, has31, k1) => parse_loop0_loop0.body input lim «end»
      head1 prev1 has31 k1)
    (head, prev, has3, k)

/-- [slot::parse]: loop body 0:
    Source: 'src/parse.rs', lines 1:0-161:5
    Visibility: public -/
@[rust_loop_body]
def parse_loop0.body
  (input : Slice Std.U8) (n : Std.Usize) (lim : Std.Usize)
  (out : Slice Std.U32) (head : Array Std.U32 32768#usize)
  (prev : Array Std.U32 32768#usize) (ntok : Std.Usize) (pos : Std.Usize)
  (has3 : Bool) :
  Result (ControlFlow ((Slice Std.U32) × (Array Std.U32 32768#usize) × (Array
    Std.U32 32768#usize) × Std.Usize × Std.Usize × Bool) (Std.Usize ×
    (Slice Std.U32)))
  := do
  if pos < n
  then
    let (head1, prev1, best_len, best_dist) ←
      if has3
      then
        if pos <= lim
        then
          do
          let i ← Slice.index_usize input pos
          let i1 ← pos + 1#usize
          let i2 ← Slice.index_usize input i1
          let i3 ← pos + 2#usize
          let i4 ← Slice.index_usize input i3
          let h ← hash3 i i2 i4
          let i5 ← Array.index_usize head h
          let start ← lift (UScalar.cast .Usize i5)
          let i6 ← pos % 32768#usize
          let prev2 ← Array.update prev i6 i5
          let i7 ← lift (UScalar.cast .U32 i1)
          let a ← Array.update head h i7
          let cap ← n - pos
          let cap1 ← if cap > 258#usize
                       then ok 258#usize
                       else ok cap
          let s ← lift (Array.to_slice prev2)
          let (best_len1, best_dist1) ← find_match input s pos cap1 start
          ok (a, prev2, best_len1, best_dist1)
        else ok (head, prev, 0#usize, 0#usize)
      else ok (head, prev, 0#usize, 0#usize)
    if best_len >= 3#usize
    then
      let i ← best_dist - 1#usize
      let i1 ← lift (UScalar.cast .U32 i)
      let i2 ← i1 * 256#u32
      let i3 ← 16777216#u32 + i2
      let i4 ← best_len - 3#usize
      let i5 ← lift (UScalar.cast .U32 i4)
      let i6 ← i3 + i5
      let s ← Slice.update out ntok i6
      let ntok1 ← ntok + 1#usize
      let «end» ← pos + best_len
      let k ← pos + 1#usize
      let (head2, prev2, has31) ←
        parse_loop0_loop0 input head1 prev1 has3 lim «end» k
      ok (cont (s, head2, prev2, ntok1, «end», has31))
    else
      let i ← Slice.index_usize input pos
      let i1 ← lift (UScalar.cast .U32 i)
      let s ← Slice.update out ntok i1
      let ntok1 ← ntok + 1#usize
      let pos1 ← pos + 1#usize
      ok (cont (s, head1, prev1, ntok1, pos1, has3))
  else ok (done (ntok, out))

/-- [slot::parse]: loop 0:
    Source: 'src/parse.rs', lines 1:0-161:5
    Visibility: public -/
@[rust_loop]
def parse_loop0
  (input : Slice Std.U8) (out : Slice Std.U32) (n : Std.Usize)
  (head : Array Std.U32 32768#usize) (prev : Array Std.U32 32768#usize)
  (ntok : Std.Usize) (pos : Std.Usize) (has3 : Bool) (lim : Std.Usize) :
  Result (Std.Usize × (Slice Std.U32))
  := do
  loop
    (fun (out1, head1, prev1, ntok1, pos1, has31) => parse_loop0.body input n
      lim out1 head1 prev1 ntok1 pos1 has31)
    (out, head, prev, ntok, pos, has3)

/-- [slot::parse]:
    Source: 'src/parse.rs', lines 116:0-163:1
    Visibility: public -/
def parse
  (input : Slice Std.U8) (out : Slice Std.U32) :
  Result (Std.Usize × (Slice Std.U32))
  := do
  let n := Slice.len input
  let head := Array.repeat 32768#usize 0#u32
  let prev := Array.repeat 32768#usize 0#u32
  let (has3, lim) ←
    if n >= 3#usize
    then do
         let lim1 ← n - 3#usize
         ok (true, lim1)
    else ok (false, 0#usize)
  parse_loop0 input out n head prev 0#usize 0#usize has3 lim

end slot
