#!/usr/bin/env bash
# Download the Silesia compression corpus (Deorowicz, silesia.polsl.pl) into
# data/benchmark/silesia/, and a small diverse subset into
# data/benchmark/silesia-subset/. Neither is committed to git -- this script
# is how anyone gets them.
#
#   scripts/download-silesia.sh            both silesia/ and silesia-subset/
#   scripts/download-silesia.sh --subset    silesia-subset/ only (~34 MB, fast)
#   scripts/download-silesia.sh --full      silesia/ only (~202 MB)
#
# Source: https://sun.aei.polsl.pl/~sdeor/index.php?page=silesia -- the standard
# reference corpus most modern compressor benchmarks (zstd, brotli, libdeflate)
# report numbers against. Files are individually bzip2-compressed.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../data/benchmark" && pwd)"
BASE_URL="https://sun.aei.polsl.pl/~sdeor/corpus"

# All 12 files in the full corpus.
ALL_FILES=(dickens mozilla mr nci ooffice osdb reymont samba sao webster xml x-ray)

# A small, kind-diverse subset: markup (xml), Polish text (reymont), a binary
# DLL (ooffice), an astronomical binary catalog (sao), a medical X-ray image
# (x-ray). ~34 MB total, each file under 10 MB, so the dev loop stays fast.
SUBSET_FILES=(xml reymont ooffice sao x-ray)

# filename -> format label, for the benchmark's analysis to group and normalize by
# file format instead of pooling raw bytes. Written as a *sibling* of each
# destination dir (silesia.formats.json next to silesia/) rather than a member of
# it, so nothing that iterates the corpus directory -- the real scoring engine
# included -- ever finds it. Neither is committed, so both are regenerated on
# every fetch, same as the corpus itself.
declare -A FORMATS=(
    [dickens]=prose
    [mozilla]=binary-tar
    [mr]=medical-image
    [nci]=chemical-database
    [ooffice]=office-binary
    [osdb]=database-binary
    [reymont]=pdf-document
    [samba]=source-tar
    [sao]=astronomical-binary
    [webster]=prose-dictionary
    [x-ray]=medical-image
    [xml]=markup
)

fetch_one() {
    local name="$1" dest_dir="$2"
    local out="$dest_dir/$name"
    if [[ -f "$out" ]]; then
        echo "  $name: already present, skipping"
        return
    fi
    echo "  $name: downloading"
    curl -sSL --fail --max-time 120 "$BASE_URL/$name.bz2" -o "$out.bz2"
    bunzip2 -f "$out.bz2"
}

write_formats() {
    local dest_dir="$1"
    shift
    local body="" name
    for name in "$@"; do
        body+="    \"$name\": \"${FORMATS[$name]}\",\n"
    done
    {
        echo '{'
        echo '    "_comment": "Maps filename -> a human-chosen format label, so benchmark analysis can group and normalize by file format instead of pooling raw bytes. Regenerated by download-silesia.sh on every fetch.",'
        printf "%b" "${body%,\\n}\n"
        echo '}'
    } > "${dest_dir}.formats.json"
}

fetch_set() {
    local dest_dir="$1"
    shift
    mkdir -p "$dest_dir"
    for name in "$@"; do
        fetch_one "$name" "$dest_dir"
    done
    write_formats "$dest_dir" "$@"
    echo "$dest_dir:"
    du -sh "$dest_dir"/* 2>/dev/null
}

mode="${1:-both}"

case "$mode" in
    --subset)
        echo "Fetching silesia-subset/ ..."
        fetch_set "$HERE/silesia-subset" "${SUBSET_FILES[@]}"
        ;;
    --full)
        echo "Fetching silesia/ (~202 MB) ..."
        fetch_set "$HERE/silesia" "${ALL_FILES[@]}"
        ;;
    both)
        echo "Fetching silesia-subset/ ..."
        fetch_set "$HERE/silesia-subset" "${SUBSET_FILES[@]}"
        echo
        echo "Fetching silesia/ (~202 MB) ..."
        fetch_set "$HERE/silesia" "${ALL_FILES[@]}"
        ;;
    *)
        echo "usage: $0 [--subset|--full]" >&2
        exit 2
        ;;
esac

echo
echo "Done. Both are already in validator/corpora.toml; point a run at one with:"
echo "  VERIFY_CORPUS=silesia-subset just bench miner/template"
echo "  VERIFY_CORPUS=silesia        just check miner/template"
echo "or make one the default by moving 'default = true' in validator/corpora.toml."
echo "  just corpora   # what is configured, and which is the default"
